### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by bdekonin** [bdekonin/ft_transcendence#42]
**Overview**
- [x] Your website backend must be written in NestJS.
- [x] The frontend must be written with a TypeScript framework of your choice.
- [x] You are free to use any library you want to in this context. However, you must use the latest stable version of every library or framework used in your project.
- [x] You must use a PostgreSQL database. That’s it, no other database.
- [x] Your website must be a single-page application. The user should be able to use the Back and Forward buttons of the browser.
- [x] Your website must be compatible with the latest stable up-to-date version of Google Chrome and one additional web browser of your choice.
- [x] The user should encounter no unhandled errors and no warnings when browsing the website.
- [x] Everything has to be launch by a single call to: docker-compose up --build

 **Security concerns**
- [x] Any password stored in your database must be hashed.
- [x] Your website must be protected against SQL injections.
- [x] You must implement some kind of server-side validation for forms and any user input.

**User Account**
- [x] The user must login using the OAuth system of 42 intranet.
- [x] The user should be able to choose a unique name that will be displayed on the website.
- [x] The user should be able to upload an avatar. If the user doesn’t upload an avatar, a default one must be set.
- [x] The user should be able to enable two-factor authentication. For instance, Google Authenticator or sending a text message to their phone.
- [x] The user should be able to add other users as friends and see their current status (online, offline, in a game, and so forth).
- [x] Stats (such as: wins and losses, ladder level, achievements, and so forth) have to be displayed on the user profile.
- [x] Each user should have a Match History including 1v1 games, ladder, and anything else useful. Anyone who is logged in should be able to consult it.

**Chat**
- [x] The user should be able to create channels (chat rooms) that can be either public, or private, or protected by a password.
- [x] The user should be able to send direct messages to other users.
- [x] The user should be able to block other users. This way, they will see no more messages from the account they blocked.
- [x] The user who has created a new channel is automatically set as the channel owner until they leave it.
- [x] • The user should be able to invite other users to play a Pong game through the chat interface.
- [x] • The user should be able to access other players profiles through the chat interface.

**Game**
- [x] Therefore, users should be able to play a live Pong game versus another player directly on the website.
- [x] There must be a matchmaking system: the user can join a queue until they get automatically matched with someone else.
- [x] It can be a canvas game, or it can be a game rendered in 3D, it can also be ugly, but in any case, it must be faithful to the original Pong (1972).
- [x] You must offer some customization options (for example, power-ups or different maps). However, the user should be able to select a default version of the game without any extra features if they want to.
- [x] The game must be responsive!
- [x] The user should be able to watch a live play between other users without interfering with it.
